### ISSUE TITLE
Data name has hard-coded index in dynamixels.py

### ISSUE THREAD

**Issue by Finchiedev** [CCGSRobotics/RoboHUD#63]
In the file `Server/Driving/dynamixels.py`, on line 241:
```py
build[line[2]] = {}
```
If the index of 'Data Name' is anything but that, the code will break. Instead, the index of 'Data Name' should be found by looking through the first line (the header) and setting it to a variable such as `data_index`. All references to `line[2]` found in the function (lines 241, 243, 247) should subsequently be replaced with `line[data_index]`.

**Comment by Finchiedev** [comment]
This has been labelled as `good first issue` to encourage new contributors to start working on this repository!

**Comment by frahmadani** [comment]
Hi, can I try working on this one?

**Comment by Finchiedev** [comment]
Absolutely! Please make a pull request when you are done :)

**Comment by frahmadani** [comment]
Hi @Finchiedev, I've submitted PR #66. I realized I didn't have the csv file to test, so this is only tested with my (assumed) csv. Hope there's nothing I missed :)
